#!/bin/bash


if [[ $EUID -ne 0 ]]; then
    echo -e "\e[31m[ERRO] Este script deve ser executado como root.\e[0m"
    exit 1
fi

COLLECTED_DIR="collected_files"
mkdir -p "$COLLECTED_DIR"

echo -e "\e[35;1mColetando arquivos do sistema..\e[0m"

echo -e "\e[35mListando informações sobre discos e partições..\e[0m"
lsblk > "$COLLECTED_DIR/disk_info.txt"

echo -e "\e[35mColetando informações de rede..\e[0m"
ss -tulnp > "$COLLECTED_DIR/active_connections.txt"
netstat -tulnp > "$COLLECTED_DIR/open_ports.txt"


echo -e "\e[35mColetando lista de processos..\e[0m"
ps aux > "$COLLECTED_DIR/process_list.txt"


echo -e "\e[35mColetando logs do sistema..\e[0m"
cp /var/log/syslog "$COLLECTED_DIR/syslog.log" 
cp /var/log/auth.log "$COLLECTED_DIR/auth.log"
cp /var/log/dmesg "$COLLECTED_DIR/dmesg.log" 


echo -e "\e[35mColetando arquivos de configuração..\e[0m"
cp -r /etc "$COLLECTED_DIR/etc_backup" 2>/dev/null

echo -e "\e[35mListando o diretório raiz..\e[0m"
ls -la / > "$COLLECTED_DIR/root_dir_list.txt"

HOSTNAME=$(hostname)
DATE=$(date +"%Y-%m-%d_%H-%M-%S")
OUTPUT_FILE="TraceHunter_${HOSTNAME}_${DATE}.tar.gz"

tar -czf "$OUTPUT_FILE" "$COLLECTED_DIR"


echo -e "\e[32mColeta finalizada! Arquivo salvo como: $OUTPUT_FILE\e[0m"
